#!/usr/bin/env python
from dbapi_opentracing import PsycopgConnectionTracing
import psycopg2

tracing = psycopg2.connect(
    dbname='crashy',
    user='crashy',
    password='crashy',
    host='localhost',
    connection_factory=PsycopgConnectionTracing,
)

tracing.cursor("Name", scrollable=False)
